#!/bin/sh
#python createdb.py (Note:done manually)
python geostats/manage.py syncdb --noinput
python mkadmin.py
mkdir -p /home/dotcloud/data/media /home/dotcloud/volatile/static
python geostats/manage.py collectstatic --noinput
